#!/usr/bin/env python2.7

import sys
sys.path.insert(0, '.')

import argparse

from apns_csr import mdm_vendor_sign_with_files

parser = argparse.ArgumentParser(
            description="Produce an Apple-formatted APNS 'push' CSR.")

parser.add_argument('key', 
                    help='client private key (PEM)')

parser.add_argument('csr', 
                    help='client CSR (PEM)')

parser.add_argument('vendor_p12', 
                    help='MDM vendor P12 certificate (DER)')

parser.add_argument('vendor_p12_pass', 
                    help='passphrase for MDM vendor P12 certificate')

parser.add_argument('-x', '--xml', 
                    help='show raw XML', action='store_true')

args = parser.parse_args()

encoded_plist = mdm_vendor_sign_with_files(
                    args.key, 
                    args.csr, 
                    args.vendor_p12, 
                    args.vendor_p12_pass, 
                    encode_xml=not args.xml)

sys.stdout.write(encoded_plist)

